INCLUDE_TOPICS_MODE: false

TOPICS_TO_EXCLUDE:
  # - /radar_detected_objs
  # - /clustered_dist2wall
  # - /clusters_with_feature
  # - /concatenate_data_synchronizer/debug/cyclic_time_ms
  # - /concatenate_data_synchronizer/debug/processing_time_ms
  # - /crop_box_filter/crop_box_polygon
  # - /crop_box_filter/debug/cyclic_time_ms
  # - /crop_box_filter/debug/processing_time_ms
  # - /debug/clusters
  # - /debug/divided_objects 
  # - /debug/initial_objects  
  # - /debug/merged_objects
  # - /debug/tracked_objects  
  # - /ego_crop_box_filter/crop_box_polygon
  # - /tracked_objects
  # - /tracker_detected_objects
  # - /debug/merged_objects
  # - /radar_liadar_detected_objects
  # - /objects
  # - /debug/tracked_objects  
  # - /debug/initial_objects  
  # - /radar_detected_objs
  # - /merged_objects
  # - /debug/divided_objects  # Add more topics to exclude here...

TOPICS_TO_INCLUDE:
  - /luminar_front_points
  - /luminar_left_points
  - /luminar_right_points


# # If INCLUDE_TOPICS_MODE is set to True, the script will only extract the topics in this list.
# TOPICS_TO_INCLUDE = {
# # Lidar Topics
# "/luminar_front_points", \
# "/luminar_left_points", \
# "/luminar_right_points", \

# # Radar Topics
# "/radar_front/radar_visz_static",\
# "/radar_front/radar_visz_static_array",\
# "/radar_front/radar_visz_moving", \
# # "/radar_front/radar_visz_moving_array",\
# "/perception/lvms_inside_vis", "/perception/lvms_outside_vis", \
# '/radar_right/marker', '/radar_front/from_can_bus',  \
# '/radar_front/to_can_bus'
# ,'/radar_front/esr_status1'\
# ,'/radar_front/esr_status2'\
# ,'/radar_front/esr_status3'\
# ,'/radar_front/esr_status4'\
# ,'/radar_front/esr_status5'\
# ,'/radar_front/esr_status6'\
# ,'/radar_front/esr_status7'\
# ,'/radar_front/esr_status8'\
# ,'/radar_front/esr_status9'\
# ,'/radar_front/esr_track'\
# ,'/radar_front/esr_valid1'\
# ,'/radar_front/esr_valid2'\
# ,'/radar_front/esr_vehicle1'\
# ,'/radar_front/esr_vehicle2'\
# ,'/radar_front/esr_vehicle3'\
# ,'/radar_front/esr_vehicle4'\
# ,'/radar_front/esr_vehicle5'\
# ,'/radar_left/detection'\
# ,'/radar_left/header_information_detections'\
# ,'/radar_left/marker'\
# ,'/radar_left/vehicle_state'\
# ,'/radar_right/detection'\
# ,'/radar_right/header_information_detections'\
# ,'/radar_right/marker'\
# # ,'/radar_right/marker_array'\
# ,'/radar_right/vehicle_state'\

# # Track Polygon
# ,'/path'\
# ,'/perception/lvms_inside'\
# ,'/perception/lvms_inside_vis'\
# ,'/perception/lvms_outside'\
# ,'/perception/lvms_outside_vis'\

# # Novatel
# ,'/novatel_bottom/bestgnsspos'\
# ,'/novatel_bottom/bestgnssvel'\
# ,'/novatel_bottom/bestpos'\
# ,'/novatel_bottom/bestutm'\
# ,'/novatel_bottom/bestvel'\
# ,'/novatel_bottom/corrimu'\
# ,'/novatel_bottom/fix'\
# ,'/novatel_bottom/gps'\
# ,'/novatel_bottom/heading2'\
# ,'/novatel_bottom/imu/data'\
# ,'/novatel_bottom/insconfig'\
# ,'/novatel_bottom/inspva'\
# ,'/novatel_bottom/inspvax'\
# ,'/novatel_bottom/insstdev'\
# ,'/novatel_bottom/odom'\
# ,'/novatel_bottom/oem7raw'\
# ,'/novatel_bottom/rawimu'\
# ,'/novatel_bottom/rxstatus'\
# ,'/novatel_bottom/time'\
# ,'/novatel_top/bestgnsspos'\
# ,'/novatel_top/bestgnssvel'\
# ,'/novatel_top/bestpos'\
# ,'/novatel_top/bestutm'\
# ,'/novatel_top/bestvel'\
# ,'/novatel_top/corrimu'\
# ,'/novatel_top/fix'\
# ,'/novatel_top/gps'\
# ,'/novatel_top/heading2'\
# ,'/novatel_top/imu/data'\
# ,'/novatel_top/insconfig'\
# ,'/novatel_top/inspva'\
# ,'/novatel_top/inspvax'\
# ,'/novatel_top/insstdev'\
# ,'/novatel_top/odom'\
# ,'/novatel_top/oem7raw'\
# ,'/novatel_top/rawimu'\
# ,'/novatel_top/rxstatus'\
# ,'/novatel_top/time'

# # /vehicle/steering_report
# # /vehicle/wheel_potentiometer_report
# # /vehicle/wheel_speed_report
# # /vehicle/wheel_strain_gauge_report
# # /visualization
# # /tracker_detected_objects
# # /ttl
# # /vehicle/engine_pressures_report
# # /vehicle/engine_report
# # /vehicle/fault_report
# # /vehicle/fl_tire_pressure
# # /vehicle/fr_tire_pressure
# # /vehicle/misc_report
# # /vehicle/reset_state
# # /vehicle/rl_tire_pressure
# # /vehicle/rr_tire_pressure
# # /vehicle/state
# # /vehicle/status
# }

FILTER_BY_TIMESTAMP: true

FROM_TIMESTAMP: 1673037588612982487
TO_TIMESTAMP: 1673037592257594379

INPUT_PATH: "/home/zhihao/rosbags/merged_rosbag/"
OUTPUT_PATH: "/home/chris/rosbags//"